[".local/lib/antigen.zsh"]
type = "file"
url = "http://git.io/antigen"
refreshPeriod = "24h"

[".local/share/nvim/site/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "24h"
